name: Kwiki-Edit-SubEtha
version: 0.02
abstract: SubEthaEdit Plugin for Kwiki
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  Kwiki: 0.33
  Kwiki::Archive::SVK: 0.01
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
